export const SET_LOCALE = 'SET_LOCALE';

export const GET_BRAND_NAME = 'GET_BRAND_NAME';

export const FETCH_DESIGNS = 'FETCH_DESIGNS';
export const FETCH_DESIGNS_SUCCEEDED = 'FETCH_DESIGNS_SUCCEEDED';
export const FETCH_DESIGNS_FAILED = 'FETCH_DESIGNS_FAILED';
